# Generated by Django 3.2.15 on 2022-08-19 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import posts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('admin_check', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itembase_related', to=settings.AUTH_USER_MODEL)),
                ('user_saved', models.ManyToManyField(blank=True, related_name='itembase_saved', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SuccessfullExperience',
            fields=[
                ('itembase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='posts.itembase')),
                ('user_liked', models.ManyToManyField(blank=True, related_name='exprience_liked', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('posts.itembase',),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('itembase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='posts.itembase')),
                ('image', models.ImageField(blank=True, default=posts.models.get_default_post_image, max_length=255, null=True, upload_to=posts.models.get_post_image_filepath)),
                ('user_liked', models.ManyToManyField(blank=True, related_name='posts_liked', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('posts.itembase',),
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('itembase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='posts.itembase')),
                ('file', models.FileField(blank=True, default=posts.models.get_default_post_image, null=True, upload_to=posts.models.get_post_image_filepath)),
                ('user_liked', models.ManyToManyField(blank=True, related_name='podcasts_liked', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('posts.itembase',),
        ),
    ]
