# Generated by Django 3.2.15 on 2022-08-19 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='itembase',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itembase_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='successfullexperience',
            name='user_liked',
            field=models.ManyToManyField(blank=True, related_name='exprience_liked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='successfullexperience',
            name='user_saved',
            field=models.ManyToManyField(blank=True, related_name='exprience_saved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='user_liked',
            field=models.ManyToManyField(blank=True, related_name='posts_liked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='user_saved',
            field=models.ManyToManyField(blank=True, related_name='posts_saved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='podcast',
            name='user_liked',
            field=models.ManyToManyField(blank=True, related_name='podcasts_liked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='podcast',
            name='user_saved',
            field=models.ManyToManyField(blank=True, related_name='podcasts_saved', to=settings.AUTH_USER_MODEL),
        ),
    ]
