# Generated by Django 3.2.15 on 2022-08-19 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itembase',
            name='admin_check',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='SuccessfulExperience',
        ),
    ]
