# Generated by Django 3.2.15 on 2022-08-19 10:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itembase',
            name='user_saved',
        ),
        migrations.AddField(
            model_name='podcast',
            name='user_saved',
            field=models.ManyToManyField(blank=True, related_name='podcasts_saved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='user_saved',
            field=models.ManyToManyField(blank=True, related_name='posts_saved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='successfullexperience',
            name='user_saved',
            field=models.ManyToManyField(blank=True, related_name='exprience_saved', to=settings.AUTH_USER_MODEL),
        ),
    ]
