# Generated by Django 3.2.15 on 2022-08-21 08:08

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='file',
            field=models.FileField(upload_to=posts.models.get_podcast_filepath),
        ),
    ]
