# Generated by Django 3.2.15 on 2022-08-19 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20220819_1222'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessfullExperience',
            fields=[
                ('itembase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='posts.itembase')),
            ],
            bases=('posts.itembase',),
        ),
    ]
