# Generated by Django 3.2 on 2022-08-28 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_podcast_owner_alter_podcast_user_liked_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f', models.IntegerField()),
                ('admin_check', models.BooleanField(default=False)),
            ],
        ),
    ]
