# Generated by Django 3.2 on 2022-08-28 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
