# Generated by Django 3.2 on 2022-09-05 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0005_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='accpeted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='user_accepted',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_accepted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='post',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project', to='posts.post'),
        ),
        migrations.AlterField(
            model_name='project',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
