# Generated by Django 3.2 on 2022-09-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20220905_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='amount',
            field=models.DecimalField(decimal_places=4, default=23, max_digits=12),
            preserve_default=False,
        ),
    ]
