# Generated by Django 3.2 on 2022-09-06 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_project_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project', to='posts.project'),
        ),
    ]
