# Generated by Django 3.2 on 2022-09-08 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0009_alter_post_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='requests',
        ),
        migrations.AddField(
            model_name='project',
            name='Preferred_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_time', models.DateTimeField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='demands',
            field=models.ManyToManyField(blank=True, related_name='project', to='posts.Demand'),
        ),
    ]
