# Generated by Django 3.2 on 2022-09-08 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0010_auto_20220908_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoldProjectMoney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.DecimalField(decimal_places=4, max_digits=12)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='posts.project')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_project_money', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_project_money', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
