# Generated by Django 3.2 on 2022-09-08 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_holdprojectmoney'),
    ]

    operations = [
        migrations.RenameField(
            model_name='holdprojectmoney',
            old_name='money',
            new_name='amount',
        ),
    ]
