# Generated by Django 3.2 on 2022-09-10 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_auto_20220910_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='accpeted',
        ),
    ]
