# Generated by Django 3.2 on 2022-09-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_remove_project_accpeted'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_money', models.DecimalField(decimal_places=4, default=0.01, max_digits=12)),
                ('podcast_money', models.DecimalField(decimal_places=4, default=0.01, max_digits=12)),
                ('comment_money', models.DecimalField(decimal_places=4, default=0.01, max_digits=12)),
            ],
        ),
    ]
