# Generated by Django 3.2 on 2022-09-13 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0018_auto_20220913_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='user_accepted',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_accepted', to=settings.AUTH_USER_MODEL),
        ),
    ]
