# Generated by Django 3.2 on 2022-09-13 13:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_alter_project_user_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='designated_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
