# Generated by Django 3.2 on 2022-09-13 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_project_designated_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='Preferred_time',
            new_name='preferred_time',
        ),
    ]
