# Generated by Django 3.2 on 2022-09-12 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_auto_20220913_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='preferred_time',
            field=models.DateTimeField(),
        ),
    ]
