# Generated by Django 3.2 on 2022-09-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0026_comment_parent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=models.TextField(default='hi', max_length=100),
            preserve_default=False,
        ),
    ]
