# Generated by Django 3.2 on 2022-09-15 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0028_podcast_cover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='podcast',
            options={'ordering': ['created_time']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['created_time']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['created_time']},
        ),
        migrations.AlterModelOptions(
            name='successfullexperience',
            options={'ordering': ['created_time']},
        ),
    ]
