BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB

BBBB BBBB

BBBBB BBBBBBBBBB gettext(u'Account Connections') BBBBBBBB

BBBBB BBBBBBB
XXXX gettext(u'Account Connections') XXXXX

BB BBBBBBBBBBBBB
XXX gettext(u'You can sign in to your account using any of the following third party accounts:') SSS SSS SSSS SS SS SSSS SSSSSSS SSSSS SSS SS SSS SSSSSSSSS SSSSS SSSSS SSSSSSSSSXXXX


XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBXX
BBBBBBBBBB

XXXXXXXXXX
BB BBBBBBBBBBBBBBBBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXX
BBBBB

BBB BBBBBBBBBBBB BB BBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBB
XXXXX
XXXXXX XXXXXXXXXXXXXXXXXX
XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX
XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX  XXXXXXXXX

XXXXXXXX
XXXXXX
BBBBBBB
BBBBBB

XXXXX
XXXXXXX XXXXXXXXXXXXXX gettext(u'Remove') XXXXXXXXX
XXXXXX

XXXXXXXXXXX

XXXXXXX

BBBB
XXX gettext(u'You currently have no social network accounts connected to this account.') XXXX
BBBBB

XXXX gettext(u'Add a 3rd Party Account') XXXXX

XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBBB
XXXXX

BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

BBBBBBBB
