BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBB
BB BBBBBBB BB BBBBBBBBB
XXXX gettext(u'Connect %(provider)s') SSSSSSS SSSSSSSSSSSSXXXXX

XXX gettext(u'You are about to connect a new third party account from %(provider)s.') SSS SSS SSSSS SS SSSSSSS S SSS SSSSS SSSSS SSSSSSS SSSS SSSSSSSSSSSSSXXXX
BBBB
XXXX gettext(u'Sign In Via %(provider)s') SSSS SS SSS SSSSSSSSSSSSXXXXX

XXX gettext(u'You are about to sign in using a third party account from %(provider)s.') SSS SSS SSSSS SS SSSS SS SSSSS S SSSSS SSSSS SSSSSSS SSSS SSSSSSSSSSSSSXXXX
BBBBB

XXXXX XXXXXXXXXXXXXX
  BBBBBBBBBB
  XXXXXXX XXXXXXXXXXXXXX gettext(u'Continue') XXXXXXXXX
XXXXXXX
BBBBBBBB
