BBBBBBB BBBBBBBBBBBBBBBBBBB

BBBB BBBB
BBBBB BBBBBBBBBB gettext(u'Change Password') BBBBBBBB

BBBBB BBBBBBB
    XXXXBB BBBBBBBBBB gettext(u'Bad Token') BBBB gettext(u'Change Password') BBBBBXXXXX

    BB BBBBBBBBBB
        BBB BBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBB
        XXX gettext(u'The password reset link was invalid, possibly because it has already been used.  Please request a <a href="%(passwd_reset_url)s">new password reset</a>.') SSS SSSSSSSS SSSSS SSSS SSS SSSSSSSS SSSSSSSS SSSSSSS SS SSS SSSSSSS SSSS SSSSS  SSSSSS SSSSSSS S SS SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS SSSSSSSS SSSSSSSSSSXXXX
    BBBB
        XXXXX XXXXXXXXXXXXX XXXXXXXXXX
            BBBBBBBBBB
            
            XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX gettext(u'change password') XXX
        XXXXXXX
    BBBBB
BBBBBBBB
