BBBBBBB BBBBBBBBBBBBBBBBBBB

BBBB BBBB

BBBBB BBBBBBBBBB gettext(u'Set Password') BBBBBBBB

BBBBB BBBBBBB
    XXXX gettext(u'Set Password') XXXXX

    XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXX
        BBBBBBBBBB
        
        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX gettext(u'Set Password') XXX
    XXXXXXX
BBBBBBBB
