BBBBBBB BBBBBBBBBBBBBBBBBBB
BBBB BBBBBB

BBBBB BBBBBBBBBBXXX XXX XXXXBBBBBBBB

BBBBB BBBBBBB

XXXX XXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XX

              BB BBBBBBBBBBB
                BBB BBBBB BB BBBB
                  BBB BBBBB BB BBBBBBBBBBBB
                      XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXX XXXXXXXXXXXXXXXXX XX
                        BB BBBBB BB BBBBB BBBBBBBB BB BBBBBBBB BBBBBBBBB
                          XXXXX XXXX XXXXXX XX XXX X XXX XXXX
                        BBBBB
                        BB BBBBB BB BBBBB BBBBBBBB BB BBB BBBBBBBB
                          XXX XX XX XXXX XXXX XX XXX XXX XXXX XXXXXXX XX XXXX
                        BBBBB
                        BB BBBBB BB BB BBBB BB BBBBBBB BBBBBBBBBB BBBB BBBB BBBBBB BBBBBBBBB
                          XXXXXX XXXX XX XXX XXXXX XXX XXX XXXX XXX
                        BBBBB
                        BB BBBBB BB BBBB BBBBBBBB BB BBB BBBBBBB BB BBB BBBBBBBBBB
                          XXX XXXX XX XXX XXXXXX XXXXX XXXXX XXXXX XXXX
                        BBBBB
                        BB BBBBB BB BBBB BBBBBBBB BB BBB BBBBBBB BB BBB BBBBBBB
                          XXX XXXX XXXXX XX XXXXX XXXXX XXXXX XXXX
                        BBBBB
                        BB BBBBB BB BBBBB BBBBBBBB BB BBB BBBBBB BB BBBB BBBBBBB BB BBBBB B BBBBBBBBBBBB
                          XXX XXXX XXXX XXXXX XX X XXXXXX XXXXX XXX XXXX
                        BBBBB
                        BB BBBBB BB BBBBBBBBBBB BBBB BBBB BBBBBBBB BBBBBBB BBBBBBBB
                          XXXXXX XXXX XX XXX XXX XXXXXX XXX XXX XXXX XXX
                        BBBBB
                      XXXXXXXXX

                    BBBBBB
                BBBBBB

              BBBBB
            XXXXXX
      XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
        BBBBBBBBBB
        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
          XXX XXX XXXX
        XXXXXXX
XXXX XXXX XXXXXXXX XX XXX XXXXXXX XXX


        
        BB BBBBBBBBBBBBBBBBBBBB
        XXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXX XX
        BBBBB
        BBBBBBBBBB
        XXXX  XXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXX XXXX XXXXXXXXXXXXXX XXXXXXXXXX
          XX XXXXXXXXXXXX XXX XXXXXXXX XXXX XX XXXX XXXX XXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
              XXX XXX
            XXXXXXXXX
          XXXXXX
        XXXXXX

      XXXXXXX
    XXXXXX
  XXXXXX
XXXXXX

BBBBBBBB
