# Generated by Django 3.2.15 on 2022-08-21 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('1', '1 Month'), ('3', '3 Month'), ('6', '6 Month'), ('12', '12 Month')], max_length=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=4, max_digits=12)),
                ('started_date', models.DateTimeField(auto_now_add=True, verbose_name='date_create')),
                ('finish_date', models.DateTimeField(blank=True, null=True, verbose_name='date_finish')),
                ('finished', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=0)),
                ('piggy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piggys', to='payment.piggybank')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
