# Generated by Django 3.2.15 on 2022-08-21 14:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_activity_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeusermodel',
            name='black_list',
            field=models.ManyToManyField(related_name='blacklist', to=settings.AUTH_USER_MODEL),
        ),
    ]
