# Generated by Django 3.2.15 on 2022-08-22 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_activity_membership_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeusermodel',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
    ]
