# Generated by Django 3.2.15 on 2022-08-18 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
        ('users', '0002_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='piggy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piggys', to='payment.piggybank'),
        ),
    ]
