# Generated by Django 3.2.15 on 2022-08-18 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_activity_piggy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('body', models.TextField()),
                ('message_type', models.CharField(choices=[('Support', 'Support'), ('Deposit', 'Deposit'), ('Error Reporting', 'Error Reporting')], max_length=20)),
                ('is_admin', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MemberShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('1', '1 Month'), ('3', '3 Month'), ('6', '6 Month'), ('12', '12 Month')], max_length=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=4, max_digits=12)),
                ('started_date', models.DateTimeField(auto_now_add=True, verbose_name='date_create')),
                ('finish_time', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
