# Generated by Django 3.2.15 on 2022-08-11 21:01

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_wallet_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet_key',
            field=models.CharField(default=users.models.create_wallet_key, editable=False, max_length=20),
        ),
    ]
