# Generated by Django 3.2.15 on 2022-08-22 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customeusermodel_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeusermodel',
            name='country',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
