# Generated by Django 3.2.15 on 2022-08-18 12:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_membership_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='finish_time',
            new_name='finished',
        ),
        migrations.AddField(
            model_name='membership',
            name='finish_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 18, 12, 48, 6, 273437, tzinfo=utc), verbose_name='date_finish'),
            preserve_default=False,
        ),
    ]
