# Generated by Django 3.2 on 2022-08-27 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
        ('users', '0004_alter_customeusermodel_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='piggy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='payment.piggybank'),
        ),
    ]
