# Generated by Django 3.2.15 on 2022-08-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20220818_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='finish_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date_finish'),
        ),
    ]
