# Generated by Django 3.2 on 2022-08-29 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_activity_piggy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeusermodel',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='customeusermodel',
            name='profile_image',
        ),
    ]
