# Generated by Django 3.2.15 on 2022-08-12 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220812_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeusermodel',
            name='country',
            field=models.CharField(choices=[('IR', 'Iran'), ('US', 'United State'), ('UK', 'United Kindom'), ('CH', 'China'), ('BR', 'Brazil'), ('FR', 'French'), ('PL', 'Poland')], default='IR', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customeusermodel',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
            preserve_default=False,
        ),
    ]
