# Generated by Django 3.2.15 on 2022-08-12 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20220812_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeusermodel',
            name='activity',
            field=models.IntegerField(default=0),
        ),
    ]
