# Generated by Django 3.2 on 2022-08-29 13:38

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profileimage_userbio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileimage',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='profileimage',
            name='image',
            field=models.ImageField(blank=True, default=users.models.get_default_profile_image, null=True, upload_to=users.models.get_profile_image_filepath),
        ),
        migrations.AlterField(
            model_name='profileimage',
            name='admin_check',
            field=models.BooleanField(default=False),
        ),
    ]
