# Generated by Django 3.2.15 on 2022-08-12 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20220812_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('1', '1 Month'), ('3', '3 Month'), ('6', '6 Month'), ('12', '12 Month')], max_length=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('started_date', models.DateTimeField(auto_now_add=True, verbose_name='date_create')),
                ('expired_day', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
