# Generated by Django 3.2 on 2022-08-30 08:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20220829_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeusermodel',
            name='black_list',
            field=models.ManyToManyField(blank=True, related_name='blacklist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userbio',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
    ]
