# Generated by Django 3.2 on 2022-08-30 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20220830_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeusermodel',
            name='name',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
