# Generated by Django 3.2.15 on 2022-08-16 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_membership_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='amount',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
    ]
