# Generated by Django 3.2 on 2022-08-30 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_customeusermodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeusermodel',
            name='profile_pic',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='users.profileimage'),
        ),
        migrations.AlterField(
            model_name='customeusermodel',
            name='user_bio',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='users.userbio'),
        ),
    ]
