# Generated by Django 3.2 on 2022-09-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20220830_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileimage',
            name='admin_check',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userbio',
            name='admin_check',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
