# Generated by Django 3.2.15 on 2022-08-16 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeusermodel',
            name='black_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blacklist', to=settings.AUTH_USER_MODEL),
        ),
    ]
