# Generated by Django 3.2.15 on 2022-08-17 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_customeusermodel_black_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='finished',
            new_name='finish_time',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='expired_day',
        ),
        migrations.AddField(
            model_name='customeusermodel',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
