# Generated by Django 3.2.15 on 2022-08-17 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20220817_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeusermodel',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='customeusermodel',
            name='day_of_birth',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customeusermodel',
            name='month_of_birth',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customeusermodel',
            name='year_of_birth',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
