# Generated by Django 3.2 on 2022-09-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_activationkey_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='activationkey',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
