# Generated by Django 3.2.15 on 2022-08-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20220817_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeusermodel',
            name='country',
            field=models.CharField(max_length=20),
        ),
    ]
