# Generated by Django 3.2 on 2022-09-04 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20220904_1849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userid',
            old_name='user_id',
            new_name='userid',
        ),
        migrations.AddField(
            model_name='customeusermodel',
            name='userid',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='users.userid'),
        ),
    ]
