# Generated by Django 3.2 on 2022-09-04 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20220904_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeusermodel',
            name='userid',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to='users.userid'),
        ),
    ]
