# Generated by Django 3.2 on 2022-09-06 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_customeusermodel_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='user',
            new_name='owner',
        ),
        migrations.AddField(
            model_name='message',
            name='user_receive',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='message_box', to='users.customeusermodel'),
            preserve_default=False,
        ),
    ]
