# Generated by Django 3.2 on 2022-09-06 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20220906_1327'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='SupportMessage',
        ),
    ]
