# Generated by Django 3.2 on 2022-09-11 09:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_userfeedbackopinion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeedbackopinion',
            name='point',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
    ]
