# Generated by Django 3.2.15 on 2022-08-12 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date create')),
                ('time', models.TimeField(editable=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_system', models.CharField(choices=[('Accept', 'Accept'), ('Reject', 'Reject'), ('Pending', 'Pending')], max_length=20)),
                ('wallet_number', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('Accept', 'Accept'), ('Reject', 'Reject'), ('Pending', 'Pending')], max_length=20)),
            ],
        ),
    ]
