# Generated by Django 3.2.15 on 2022-08-12 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('1 Month', '1'), ('3 Month', '3'), ('6 Month', '6'), ('12 Month', '12')], max_length=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('started_date', models.DateTimeField(auto_now_add=True, verbose_name='date_create')),
                ('expired_day', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
