# Generated by Django 3.2.15 on 2022-08-19 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='piggybank',
            options={'ordering': ['started_time']},
        ),
        migrations.AddField(
            model_name='piggybank',
            name='long',
            field=models.BooleanField(default=False),
        ),
    ]
