# Generated by Django 3.2 on 2022-09-01 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_transactionhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionhistory',
            name='plus',
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='kind',
            field=models.CharField(choices=[('withdraw', 'withdraw'), ('deposit', 'deposit'), ('listen', 'listen'), ('like', 'like'), ('membership', 'membership'), ('piggy', 'piggy')], max_length=20),
        ),
    ]
