# Generated by Django 3.2.15 on 2022-08-19 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0002_payment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='piggybank',
            name='current',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='piggybank',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_piggy', to='users.customeusermodel'),
            preserve_default=False,
        ),
    ]
