# Generated by Django 3.2.15 on 2022-08-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_piggybank_finish_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piggybank',
            name='started_time',
            field=models.DateTimeField(),
        ),
    ]
