# Generated by Django 3.2 on 2022-09-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20220901_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistory',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
