# Generated by Django 3.2 on 2022-09-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_transactionhistory_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistory',
            name='kind',
            field=models.CharField(choices=[('withdraw', 'withdraw'), ('deposit', 'deposit'), ('listen', 'listen'), ('like', 'like'), ('membership', 'membership'), ('piggy', 'piggy'), ('donate', 'donate')], max_length=20),
        ),
    ]
