# Generated by Django 3.2.15 on 2022-08-12 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PiggyBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('started_time', models.DateTimeField(auto_now_add=True, verbose_name='date create')),
                ('expired_day', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='time',
            new_name='created_time',
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_system',
            field=models.CharField(choices=[('Bitcoin', 'Bitcoin'), ('Visa', 'Visa'), ('Ether', 'Ether')], max_length=20),
        ),
    ]
