# Generated by Django 3.2.15 on 2022-08-13 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_payment_payment_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_system',
            field=models.CharField(choices=[('Bitcoin', 'Bitcoin'), ('Visa', 'Visa'), ('Ether', 'Ether')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Accept', 'Accept'), ('Reject', 'Reject'), ('Pending', 'Pending')], default='Pending', max_length=20),
        ),
    ]
