# Generated by Django 3.2.15 on 2022-08-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_auto_20220813_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
