# Generated by Django 3.2.15 on 2022-08-16 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_payment_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='piggybank',
            name='amount',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
    ]
