# Generated by Django 3.2.15 on 2022-08-17 08:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_auto_20220816_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='piggybank',
            name='finish_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date create'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='piggybank',
            name='started_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
