# Generated by Django 4.1 on 2022-08-24 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_rename_user_contact_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='owner',
        ),
        migrations.AddField(
            model_name='message',
            name='contact',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.contact'),
            preserve_default=False,
        ),
    ]
