# Generated by Django 4.1 on 2022-08-25 07:11

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_chat_contact_message_remove_dddd_messages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='unique_code',
            field=models.CharField(default=chat.models.UniqueGenerator, max_length=35),
        ),
    ]
