import os
from pathlib import Path

from configurations import Configuration
from configurations import values

import datetime

class Dev(Configuration):
    DEBUG = True

    """
    Django settings for core project.

    Generated by 'django-admin startproject' using Django 3.2.7.

    For more information on this file, see
    https://docs.djangoproject.com/en/3.2/topics/settings/

    For the full list of settings and their values, see
    https://docs.djangoproject.com/en/3.2/ref/settings/
    """

    from pathlib import Path

    # Build paths inside the project like this: BASE_DIR / 'subdir'.
    BASE_DIR = Path(__file__).resolve().parent.parent


    # Quick-start development settings - unsuitable for production
    # See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

    # SECURITY WARNING: keep the secret key used in production secret!
    SECRET_KEY = 'django-insecure-r_dhbumw7el)58j7w-l7)2=nvc2^^lwl8b+4grua--qg-3yohx'

    # SECURITY WARNING: don't run with debug turned on in production!

    ALLOWED_HOSTS = ['*']


    # Application definition

    INSTALLED_APPS = [
        'django.contrib.admin',
        'django.contrib.auth',
        'django.contrib.contenttypes',
        'django.contrib.sessions',
        'django.contrib.messages',
        'django.contrib.staticfiles',
        'django.contrib.sites',

        # my own app
        'users',
        'homepage',
        'payment',
        'posts',
        'chat',
        
        # third package party
        'allauth',
        'allauth.account',
        'allauth.socialaccount',
        # "debug_toolbar",
        'embed_video',
        'rest_framework',
        # 'versatileimagefield',
        'rest_framework_simplejwt',
        # 'django_nose',
        'drf_yasg',
        # 'rest_framework.authtoken',
        'dj_rest_auth',
        'dj_rest_auth.registration',
        'rest_framework.authtoken',
        'channels',
        'django_celery_beat',
        "corsheaders",
        'django_countries',


    ]
    SITE_ID = 1
    # debug tool bar
    INTERNAL_IPS = ["127.0.0.1",]

    # add django noise
    TEST_RUNNER = 'django_nose.NoseTestSuiteRunner'

    # Tell nose to measure coverage on the 'foo' and 'bar' apps
    NOSE_ARGS = [
        '--with-coverage',
        '--cover-package=courses.api.views,courses.api.permissions,courses.api.serializer,courses.views',
    ]


    MIDDLEWARE = [
        'django.middleware.security.SecurityMiddleware',
        'django.contrib.sessions.middleware.SessionMiddleware',
        "corsheaders.middleware.CorsMiddleware",
        'django.middleware.common.CommonMiddleware',
        'django.middleware.csrf.CsrfViewMiddleware',
        'django.contrib.auth.middleware.AuthenticationMiddleware',
        'django.contrib.messages.middleware.MessageMiddleware',
        'django.middleware.clickjacking.XFrameOptionsMiddleware',
        # add debug toolbar
        # "debug_toolbar.middleware.DebugToolbarMiddleware",

    ]
    # change it in development
    CORS_ALLOW_ALL_ORIGINS =True
    CORS_URLS_REGEX = r"/api/v1/.*"


    ROOT_URLCONF = 'core.urls'

    TEMPLATES = [
        {
            'BACKEND': 'django.template.backends.django.DjangoTemplates',
            'DIRS': [
                os.path.join(BASE_DIR, "/templates"),
                os.path.join(BASE_DIR, "templates"),
            ],
            'APP_DIRS': True,
            'OPTIONS': {
                'context_processors': [
                    'django.template.context_processors.debug',
                    'django.template.context_processors.request',
                    'django.contrib.auth.context_processors.auth',
                    'django.contrib.messages.context_processors.messages',
                ],
            },
        },
    ]

    # WSGI_APPLICATION = 'core.wsgi.application'
    WSGI_APPLICATION = 'core.wsgi.application'
    ASGI_APPLICATION = 'core.asgi.application'
    # CHANNEL_LAYERS = {
    #     'default': {
    #         'BACKEND': 'channels_redis.core.RedisChannelLayer',
    #         'CONFIG': {
    #             "hosts": [("redis://:WWajSJ3RKfPqJ1KwaJAM7wvsfZkjFvpv@redis-18063.c282.east-us-mz.azure.cloud.redislabs.com:18063/")],
    #         },
    #     },
    # }
    # CHANNEL_LAYERS = {
    # "default": {
    #     "BACKEND": "channels.layers.InMemoryChannelLayer"
    #     }
    # }

    # Database
    # https://docs.djangoproject.com/en/3.2/ref/settings/#databases

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite6',
        }
        # 'default': {
        #     'ENGINE': 'django.db.backends.postgresql_psycopg2',
        #     'NAME': 'django_starter4', 
        #     'USER': 'postgres', 
        #     'PASSWORD': 'est14641',
        #     'HOST': '127.0.0.1', 
        #     'PORT': '5432',
        # }
    }


    # Password validation
    # https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

    AUTH_PASSWORD_VALIDATORS = [
        {
            'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
        },
        {
            'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        },
        {
            'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
        },
        {
            'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
        },
    ]


    # Internationalization
    # https://docs.djangoproject.com/en/3.2/topics/i18n/

    LANGUAGE_CODE = 'en-us'

    TIME_ZONE = 'UTC'

    USE_I18N = True

    USE_L10N = True

    USE_TZ = True


    # Static files (CSS, JavaScript, Images)
    # https://docs.djangoproject.com/en/3.2/howto/static-files/

    STATIC_URL = '/static/'

    # Default primary key field type
    # https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

    DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


    # add email backends
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'


    # allauth settings

    AUTH_USER_MODEL = 'users.CustomeUserModel'

    ACCOUNT_EMAIL_REQUIRED = True
    ACCOUNT_UNIQUE_EMAIL = True
    ACCOUNT_AUTHENTICATION_METHOD = 'email'
    ACCOUNT_LOGIN_ON_PASSWORD_RESET = True
    ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
    
    # add incaseSensetive authentication
    AUTHENTICATION_BACKENDS = (
        'allauth.account.auth_backends.AuthenticationBackend',
        'django.contrib.auth.backends.ModelBackend',
        'users.backends.CaseInSensitiveModelBackend'
    )

    from django.urls import reverse_lazy, reverse
    LOGIN_REDIRECT_URL = reverse_lazy('users:profile')
    # LOGIN_REDIRECT_URL = '/'
    ACCOUNT_CONFIRM_EMAIL_ON_GET = True
    LOGIN_URL = 'http://localhost:8000/api/v1/accounts/login'


    ACCOUNT_FORMS = {
        'login': 'accounts.forms.CustomSignInForm',
        'signup': 'accounts.forms.CustomSignupForm',
        'add_email': 'allauth.account.forms.AddEmailForm',
        'change_password': 'accounts.forms.CustomChangePasswordForm',
        'set_password': 'allauth.account.forms.SetPasswordForm',
        'reset_password': 'allauth.account.forms.ResetPasswordForm',
        'reset_password_from_key': 'allauth.account.forms.ResetPasswordKeyForm',
        'disconnect': 'allauth.socialaccount.forms.DisconnectForm',
    }

    # add loggoing
    LOGGING = {    
        'version': 1,
        'disable_existing_loggers': False,
        'incremental': True,
        'root': {
            'level': 'DEBUG',
        },
    }
     # Static files (CSS, JavaScript, Images)
    # https://docs.djangoproject.com/en/3.2/howto/static-files/
    
    STATIC_URL = '/static/'
    STATIC_ROOT = os.path.join(BASE_DIR, 'static')


    MEDIA_URL = '/media/'
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

    # add rest_framework
    REST_FRAMEWORK = {
        "DEFAULT_AUTHENTICATION_CLASSES" : [
            "rest_framework.authentication.SessionAuthentication",
            'rest_framework_simplejwt.authentication.JWTAuthentication',
            'dj_rest_auth.jwt_auth.JWTCookieAuthentication',
        ],
        # Use Django's standard `django.contrib.auth` permissions,
        # or allow read-only access for unauthenticated users.
        'DEFAULT_PERMISSION_CLASSES': [
            'rest_framework.permissions.AllowAny'
        ],
        # "DEFAULT_PERMISSION_CLASSES" : [
        #     "rest_framework.permissions.IsAuthenticatedOrReadOnly", # GET
        # ],
        "DEFAULT_PAGINATION_CLASS" : "rest_framework.pagination.PageNumberPagination",
        "PAGE_SIZE" : 4,
    }
    SIMPLE_JWT = {
        'ACCESS_TOKEN_LIFETIME': datetime.timedelta(days=1),
        'REFRESH_TOKEN_LIFETIME': datetime.timedelta(days=7),
    }
    # AUTH_PROFILE_MODULE = 'users.MyUser'
    # EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = 'smtp.gmail.com'
    EMAIL_USE_TLS = True
    EMAIL_PORT = 587
    EMAIL_HOST_USER = "omid.pakshekar.est@gmail.com"
    EMAIL_HOST_PASSWORD = "pyebmokthohxraze"
    DEFAULT_FROM_EMAIL = 'omid.pakshekar.est@gmail.com'
    # enable rest_jwt
    REST_USE_JWT = True
    JWT_AUTH_COOKIE = 'my-app-auth'
    # REST_AUTH_SERIALIZERS = {
    #     'USER_DETAILS_SERIALIZER': 'accounts.serializers.CustomUserDetailsSerializer',
    #     'PASSWORD_RESET_SERIALIZER': 'accounts.serializers.CustomPasswordResetSerializer',
    # }

    REST_AUTH_REGISTER_SERIALIZERS = {
        'REGISTER_SERIALIZER': 'users.api.serializers.CustomRegisterSerializer',
    }
    ACCOUNT_ADAPTER = 'users.adapter.CustomAccountAdapter'
    REST_AUTH_SERIALIZERS = {
        'LOGIN_SERIALIZER': 'users.api.serializers.LoginSerializer',
    }
    # django_celery_beat
        
    CELERY_BEAT_SCHEDULE = {
        "scheduled_task_check_piggy" : {
            "task" : "payment.tasks.check_piggy",
            "schedule" : 30.0,
        },
        "scheduled_task_check_membership" : {
            "task" : "users.tasks.check_membership",
            "schedule" : 50.0,
        },
    }
    CELERY_BROKER_URL = "redis://default:I975B8xRZqKuwChLgpAstgyitOESUKcr@redis-10353.c90.us-east-1-3.ec2.cloud.redislabs.com:10353/0"
    # CELERY_BROKER_URL = "redis://redis-18063.c282.east-us-mz.azure.cloud.redislabs.com:18063"
    # CELERY_ACCEPT_CONTENT = ['json']
    # CELERY_TASK_SERIALIZER = 'json'
    # REDIS_HOSTNAME = "redis-18063.c282.east-us-mz.azure.cloud.redislabs.com"
    # REDIS_PORT= "18063"
    # REDIS_PASSWORD = "WWajSJ3RKfPqJ1KwaJAM7wvsfZkjFvpv"

    JWT_AUTH_RETURN_EXPIRATION = True
class Prod(Dev):
    DEBUG = False



