BBBBBBB BBBBBBBBBBBBBBBBBB

BBBB BBBB

BBBBB BBBBBBBBBBXXXXXX XXXX XXBBBBBBBB

BBBBB BBBBBBB

XXXX gettext(u'OpenID Sign In') XXXXX


XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBXX
BBBBBBBBBB

XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX
XXXXXXX

BBBBBBBB
